import '../data/model/iqra.dart';

var iqraList = [
  Iqra(name: 'Iqra 1', images: iqra1),
  Iqra(name: 'Iqra 2', images: iqra2),
  Iqra(name: 'Iqra 3', images: iqra3),
  Iqra(name: 'Iqra 4', images: iqra4),
  Iqra(name: 'Iqra 5', images: iqra5),
  Iqra(name: 'Iqra 6', images: iqra6),
];

var iqra1 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/30_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_1/31_result-min.jpg',
];

var iqra2 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_2/30_result-min.jpg',
];

var iqra3 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_3/30_result-min.jpg',
];

var iqra4 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_4/30_result-min.jpg',
];

var iqra5 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_5/30_result-min.jpg',
];

var iqra6 = [
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/1_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/2_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/3_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/4_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/5_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/6_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/7_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/8_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/9_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/10_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/11_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/12_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/13_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/14_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/15_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/16_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/17_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/18_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/19_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/20_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/21_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/22_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/23_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/24_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/25_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/26_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/27_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/28_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/29_result-min.jpg',
  'https://raw.githubusercontent.com/zuludin04/asmaul_husna/main/images/iqra_6/30_result-min.jpg',
];
