name: islamic_feature
description: Collection of islamic feature
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^0.20.1
  flutter_vibrate: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - packages/islamic_feature/assets/asmaul_husna.json
    - packages/islamic_feature/assets/dzikir.json
    - packages/islamic_feature/assets/book.png
